name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    example_matrix:
      strategy:
        matrix:
          os: [ [ubuntu-latest, windows-latest], macos-latest ]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
            cache: maven
        - name: Build and run tests (Allure)
          run: mvn test --batch-mode -Dmaven.test.failure.ignore=true -PAllure
        - name: Build and run tests (JaCoCo)
          run: mvn test --batch-mode -Dmaven.test.failure.ignore=true -PJaCoCo
        - name: Publish test report (JaCoCo)
          uses: starburstdata/action-testng-report@v1
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and run tests (Parameters)
          run: mvn test --batch-mode -Dmaven.test.failure.ignore=true -PParameters
        - name: Publish test report (Parameters)
          uses: starburstdata/action-testng-report@v1
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}


