name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build and run tests (Allure)
        run: mvn test --batch-mode -Dmaven.test.failure.ignore=true -PAllure
      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
      - name: Build and run tests (JaCoCo)
        run: mvn test --batch-mode -Dmaven.test.failure.ignore=true -PJaCoCo
      - name: Publish test report (JaCoCo)
        uses: starburstdata/action-testng-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and run tests (Parameters)
        run: mvn test --batch-mode -Dmaven.test.failure.ignore=true -PParameters
      - name: Publish test report (Parameters)
        uses: starburstdata/action-testng-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
